-- This script creates the main 'users' table for the Tranqilo application.

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       username VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(255) NOT NULL,
                       first_name VARCHAR(255),
                       last_name VARCHAR(255),
                       email VARCHAR(255),
                       birth_date DATE,
                       profile_picture_url VARCHAR(255),
                       coach_id BIGINT,
                       CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Add constraints for unique fields
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT uc_users_username UNIQUE (username);

-- Add the foreign key for the self-referencing coach-client relationship
ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_COACH FOREIGN KEY (coach_id) REFERENCES users (id);